### ISSUE TITLE
Not working in CakePHP Version 3.2.3

### ISSUE THREAD

**Issue by tushar4monto** [sherwinrobles/CakeAdminLTE#1]
Hello
Please Provide Step by Step Details how i can use this in version 3.2.3
Thanks

**Comment by kwijibo82** [comment]
Seems that not works with the latest versions of CakePHP :(
Can you provide more info about this?

Thanks in advance.

**Comment by sherwinrobles** [comment]
Hi you could use cakeswatch for cakephp 3+ then change css from webroot  : https://github.com/sherwinrobles/Cakeswatch

**Comment by tushar4monto** [comment]
Thanks for this solution
